In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder


In [2]:
data=pd.read_excel('dataGYM.xlsx')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         1176 non-null   int64  
 1   Height      1176 non-null   float64
 2   weight      1176 non-null   int64  
 3   BMI         1176 non-null   int64  
 4   Class       1176 non-null   object 
 5   Prediction  1176 non-null   object 
 6   Unnamed: 6  0 non-null      float64
dtypes: float64(2), int64(3), object(2)
memory usage: 64.4+ KB


In [4]:
data.head()

Age  Height  weight  BMI            Class  \
0   48     4.1      86   40  Extremely obese   
1   53     4.1      91   42  Extremely obese   
2   42     4.1      95   44  Extremely obese   
3   48     4.1     100   46  Extremely obese   
4   22     4.1     104   48  Extremely obese   

                                          Prediction  Unnamed: 6  
0  Extremely obese--normal exercise+yoga+heavy di...         NaN  
1  Extremely obese--normal exercise+yoga+heavy di...         NaN  
2  Extremely obese--normal exercise+yoga+heavy di...         NaN  
3  Extremely obese--normal exercise+yoga+heavy di...         NaN  
4  Extremely obese--normal exercise+yoga+heavy di...         NaN

In [5]:
df = data.copy()
del df['BMI']
del df['Class']
del df['Unnamed: 6']
label_encoder = LabelEncoder()
df['Prediction'] = label_encoder.fit_transform(df['Prediction'])

In [6]:
df

Age  Height  weight  Prediction
0      48     4.1      86           0
1      53     4.1      91           0
2      42     4.1      95           0
3      48     4.1     100           0
4      22     4.1     104           0
...   ...     ...     ...         ...
1171   50     6.9      59           4
1172   49     6.9      64           4
1173   52     6.9      68           4
1174   36     6.9      73           4
1175   26     6.9      77           4

[1176 rows x 4 columns]

In [7]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]



In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [9]:
model_GYM = RandomForestClassifier(n_estimators=20)

model_GYM.fit(X_train, y_train)

print(model_GYM)

RandomForestClassifier(n_estimators=20)


In [14]:
 #make predictions
expected = y_test
predicted = model_GYM.predict(X_test)
# summarize the fit of the model



In [16]:
#Correction
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92        36
           1       0.69      0.78      0.73        49
           2       0.85      0.85      0.85        53
           3       0.74      0.61      0.67        46
           4       0.90      0.87      0.88        52

    accuracy                           0.81       236
   macro avg       0.81      0.81      0.81       236
weighted avg       0.81      0.81      0.81       236

[[35  0  1  0  0]
 [ 0 38  0  7  4]
 [ 5  0 45  3  0]
 [ 0 10  7 28  1]
 [ 0  7  0  0 45]]


In [12]:
import pickle

pickle.dump(model_GYM, open("Model_GYM.pkl", "wb"))

model = pickle.load(open("Model_GYM.pkl", "rb"))

print(model.predict([[40,5.6,70]]))


[1]
